Redo errors reporting
Makes all errors and exceptions go to an OutputPanel view. In order to
achieve that, all exception-throwing operations (literally any Python
statement) were moved into the build() function inside the try-catch
block.

I'm not very happy with the control flow exception SilentException, but
exceptions are evil anyway, so that just happened to be the simplest way
to avoid printing dummy traceback.

It also reverses the order of 'Building' and 'Compiling' stages in the
output, because this is how it matches the actual workflow and makes
error reporting at each stage more meaningful, i.e. all errors related
to the source file processing now will be displayed after the
'Compiling <source>' line, and the 'Building <target>' line won't get
reached up until serializing yaml and writing the the target file.

Improves logging format and right-aligns messages on their first word.
Makes '[Finished ...]' line format more consistent with other build
systems, e.g. C Single File from C++ community package.
For example:

   Compiling Amazing.sublime-syntax.yaml-macros (/AmazingLanguage/Amazing.sublime-syntax.yaml-macros)
    Building Amazing.sublime-syntax (/AmazingLanguage/Amazing.sublime-syntax)
   [Finished in 0.0s]

And below are logs of some failed builds, indented with 2 extra spaces
and edited for sensitive filesystem paths.

- Attempt to build something which is not YAML Macros:

     Compiling amazing_macros.py (/AmazingLanguage/amazing_macros.py)

  Error: Source is not a YAML Macros file!
  Hint: Make sure source file has `.sublime-syntax.yaml-macros` extension.

  [Finished in 0.0s with errors]

- Failed chdir due to nonexistent directory:

     Compiling Amazing.sublime-syntax.yaml-macros (/AmazingLanguage/tmp/Amazing.sublime-syntax.yaml-macros)

  Traceback (most recent call last):
    File "<Packages>/YAMLMacros/src/build.py", line 77, in build
      os.chdir(working_dir)
  FileNotFoundError: [Errno 2] No such file or directory: '/AmazingLanguage/tmp'

  [Finished in 0.0s with errors]

- Wrong macro name:

     Compiling Amazing.sublime-syntax.yaml-macros (/AmazingLanguage/Amazing.sublime-syntax.yaml-macros)

  Unknown macro "wraps".
    in "<file>", line 37, column 14

  Traceback (most recent call last):
    File "<Packages>/YAMLMacros/src/engine.py", line 64, in multi_constructor
      macro = macros[suffix]
  KeyError: 'wraps'

  [Finished in 0.0s with errors]

- Write-protected target:

     Compiling Amazing.sublime-syntax.yaml-macros (/AmazingLanguage/Amazing.sublime-syntax.yaml-macros)
      Building Amazing.sublime-syntax (/AmazingLanguage/Amazing.sublime-syntax)
  
  Traceback (most recent call last):
    File "<Packages>/YAMLMacros/src/build.py", line 85, in build
      with open(target_path, 'w') as output_file:
  PermissionError: [Errno 13] Permission denied: '/AmazingLanguage/Amazing.sublime-syntax'
  
  [Finished in 0.0s with errors]


Fully fixes #35